[project]
name = ""
version = ""
description = ""
authors = [
    {name = "NightFeather", email = "leolee50910@gmail.com"},
]
dependencies = [
    "uvicorn>=0.22.0",
    "fastapi>=0.95.2",
]
requires-python = ">=3.11"
license = {text = "MIT"}

